[package]
name = "hex2bin"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]
edition = "2018"

[dependencies]
memmap = "0.7"
structopt = "0.2.13"
log = "0.4.6"
env_logger = "0.5.13"
failure = "0.1.3"
rayon = "1.0.3"
num_cpus = "1.8.0"
